/communication_hub:
  ros__parameters:
    enable_default_chat: false
    chatbot_startup_timeout: 60.
    chatbot_response_timeout: 15.
    chatbot: chatbot_ollama
    multi_modal_expression_timeout: 30.
  # remappings:
  #   chatbot/start_dialogue/_action/feedback: chatbot_ollama/start_dialogue/_action/feedback
  #   chatbot/start_dialogue/_action/status: chatbot_ollama/start_dialogue/_action/status
  #   chatbot/start_dialogue/_action/send_goal: chatbot_ollama/start_dialogue/_action/send_goal
  #   chatbot/start_dialogue/_action/cancel_goal: chatbot_ollama/start_dialogue/_action/cancel_goal
  #   chatbot/start_dialogue/_action/get_result: chatbot_ollama/start_dialogue/_action/get_result
  #   chatbot/dialogue_interaction: chatbot_ollama/dialogue_interaction
/chatbot_ollama:
  ros__parameters:
    temperature: 0.0
    # server_url: http://143.225.85.134:11434
    # model_name: phi4
    api_key: "<insert_your_api_key_here>"
    server_url: https://api.openai.com
    model_name: 'gpt-4.1-mini'
